export interface BaselineEntryFields {
  startDate: string;
  endDate: string;
  invoiceDate: string;
  noOfDays: string;
  kwh: string;
  minKw: string;
  maxKw: string;
  avgKw: string;
  avgKva: string;
  pf: string;
  minPf: string;
  maxPf: string;
  rate: string;
  energyRate: string;
  fuelRate: string;
  ippRate: string;
  ippCharge: string;
  fuelCharge: string;
  kvaRate: string;
  ippVariableRate: string;
  ippFixedRate: string;
  ippVariableCharge: string;
  ippFixedCharge: string;
  energyCharge: string;
  kvaCharge: string;
  currentCharges: string;
  salesTax: string;
}
